### ISSUE TITLE
Build breaks on old versions of GCC

### ISSUE THREAD

**Issue by ullenius** [koitsu/nsfinfo#5]
I tried building on an old Linux machine running gcc 4.6.3 (2011) and GNU make 3.81 (2006) and ran into failures:

```sh
cc -c -g3 -ggdb -Werror -Wall -Wextra -Wformat-security -Waggregate-return -Wbad-function-cast -Wcast-align -Wdeclaration-after-statement -Wdisabled-optimization -Wfloat-equal -Winline -Wmissing-declarations -Wmissing-prototypes -Wnested-externs -Wold-style-definition -Wpacked -Wpointer-arith -Wredundant-decls -Wstrict-prototypes -Wunreachable-code -Wwrite-strings -o md5.o md5.c
cc -c -g3 -ggdb -Werror -Wall -Wextra -Wformat-security -Waggregate-return -Wbad-function-cast -Wcast-align -Wdeclaration-after-statement -Wdisabled-optimization -Wfloat-equal -Winline -Wmissing-declarations -Wmissing-prototypes -Wnested-externs -Wold-style-definition -Wpacked -Wpointer-arith -Wredundant-decls -Wstrict-prototypes -Wunreachable-code -Wwrite-strings -o sha256.o sha256.c
cc -g3 -ggdb -Werror -Wall -Wextra -Wformat-security -Waggregate-return -Wbad-function-cast -Wcast-align -Wdeclaration-after-statement -Wdisabled-optimization -Wfloat-equal -Winline -Wmissing-declarations -Wmissing-prototypes -Wnested-externs -Wold-style-definition -Wpacked -Wpointer-arith -Wredundant-decls -Wstrict-prototypes -Wunreachable-code -Wwrite-strings -o nsfinfo nsfinfo.c md5.o sha256.o
nsfinfo.c: In function 'my_MD5_File':
nsfinfo.c:107:2: error: 'for' loop initial declarations are only allowed in C99 mode
nsfinfo.c:107:2: note: use option -std=c99 or -std=gnu99 to compile your code
nsfinfo.c: In function 'my_SHA256_File':
nsfinfo.c:163:2: error: 'for' loop initial declarations are only allowed in C99 mode
make: *** [nsfinfo] Error 1
```

I added `-std=c99` to the `CFLAGS` and then I got POSIX related failures instead:
```sh
nsfinfo.c: In function 'main':
nsfinfo.c:235:2: error: implicit declaration of function 'getopt' [-Werror=implicit-function-declaration]
nsfinfo.c:235:2: error: nested extern declaration of 'getopt' [-Werror=nested-externs]
nsfinfo.c:247:10: error: 'optind' undeclared (first use in this function)
nsfinfo.c:247:10: note: each undeclared identifier is reported only once for each function it appears in
cc1: all warnings being treated as errors
make: *** [nsfinfo] Error 1
```

**Comment by koitsu** [comment]
This is caused by a missing #include somewhere.  The problem is that it's going to vary per OS distribution and compiler.  You will need to verify on a per-distro and per-compiler basis.

On FreeBSD 11.x, the function and optind/opterr/optopt/optarg globals are all made available through `#include <unistd.h>`.  The same applies to Ubuntu 22.04.6 and Ubuntu 20.04.  You can verify this through `man 3 getopt`.

**Comment by koitsu** [comment]
https://stackoverflow.com/a/22576057 implies this is solved by **not** using `-std=c99`.  `unistd.h` is supposed to pull this in normally, but on some systems `#include <getopt.h>` might be needed on older OSes or compilers.  You will need to do the deep digging.  No hacks/kludges, really do the necessary effort.  Please test/verify.  Again: this software is not C99-oriented.

**Comment by ullenius** [comment]
Thanks for your effort and digging.

It seems the C99-flag might have caused the issue with GCC (4.6.3). It enforces "strict ISO standard C99" (no extensions) causing POSIX-things to fail.

Everything worked out of the box when I simply moved the counter variables C89-style as per [your suggestion](https://github.com/koitsu/nsfinfo/pull/6#issuecomment-1631481185).

> Again: this software is not C99-oriented.

Thanks for clarifying. I wrongly presumed it was allowed in new code.

PS: Once again thanks for a great piece of software with high-quality C code.
